---
- name: Install python3, docker and docker-compose
  hosts: web_server
  become: yes
  tasks:
  - name: Install python3 and docker
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum: 
      name: 
        - python3
        - docker
      update_cache: yes
      state: present
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: +x
  - name: Install docker python dependency
    pip:
      name: 
        - docker
        - docker-compose

- name: Start docker
  hosts: web_server
  become: yes
  tasks:
  - name: Start docker daemon
    systemd:
      name: docker
      state: started

- name: Add ec2-user to docker group
  hosts: web_server
  become: yes
  tasks:
  - name: Add ec2-user to docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnect to server session
    meta: reset_connection

- name: Run web application
  hosts: web_server
  tasks:
  - name: Copy docker compose file
    copy:
      src: docker-compose.yaml
      dest: /home/ec2-user/docker-compose.yaml
  - name: Start containers from compose
    community.docker.docker_compose:
      project_src: /home/ec2-user
      state: present